export const COLORS = {
  pink: '#FF6B9D',
  pinkHot: '#FF4088',
  pinkLight: '#FFB3D0',
  pinkSoft: '#FFE0EC',
  pinkPale: '#FFF0F5',
  magenta: '#E8368F',
  berry: '#C7266A',
  lavender: '#D4A5FF',
  lavenderSoft: '#F0E0FF',
  lilac: '#B388FF',
  mint: '#7DDDB5',
  mintSoft: '#D4F5E6',
  peach: '#FFB088',
  peachSoft: '#FFE5D6',
  yellow: '#FFD966',
  coral: '#FF8A80',
  white: '#FFFFFF',
  cream: '#FFFAFC',
  offWhite: '#FFF5F8',
  grayLight: '#F5EAF0',
  grayMid: '#E0D4DC',
  textDark: '#3D1F33',
  textMid: '#7A5068',
  textMuted: '#B894A6',
  charcoal: '#2A1522',
  gold: '#FFB740',
  red: '#FF4D6A',
  green: '#55C98A',
} as const;

export const SWATCHES = [
  { name: 'Pink', color: '#FF6B9D' },
  { name: 'Lavender', color: '#B388FF' },
  { name: 'Blue', color: '#64B5F6' },
  { name: 'Mint', color: '#7DDDB5' },
  { name: 'Peach', color: '#FFB088' },
  { name: 'Red', color: '#FF4D6A' },
  { name: 'Gold', color: '#FFB740' },
  { name: 'Berry', color: '#C7266A' },
] as const;
